### ISSUE TITLE
NotFoundError: rnnlm/multi_rnn_cell/cell_0/gru_cell/candidate/kernel

### ISSUE THREAD

**Issue by dylib** [zenixls2/chatbot-rnn#1]
Hello, when I try and run the `chatbot.py` I get the following error:
```
NotFoundError (see above for traceback): Tensor name 
"rnnlm/multi_rnn_cell/cell_0/gru_cell/candidate/kernel" not found in checkpoint files 
models/reddit/model.ckpt-4682964
	 [[Node: save/RestoreV2_5 = RestoreV2[dtypes=[DT_FLOAT], 
_device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, 
save/RestoreV2_5/tensor_names, save/RestoreV2_5/shape_and_slices)]]
```
More specifically the error says:
```
raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Tensor name 
"rnnlm/multi_rnn_cell/cell_0/gru_cell/gates/bias" not found in checkpoint files 
models/reddit/model.ckpt-4682964
	 [[Node: save/RestoreV2_6 = RestoreV2[dtypes=[DT_FLOAT], 
_device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, 
save/RestoreV2_6/tensor_names, save/RestoreV2_6/shape_and_slices)]]

Caused by op u'save/RestoreV2_6', defined at:
  File "chatbot.py", line 301, in <module>
    main()
  File "chatbot.py", line 35, in main
    sample_main(args)
  File "chatbot.py", line 71, in sample_main
    saver = tf.train.Saver(net.save_variables_list())
```
How do I restore the model from the provided checkpoint? Thanks!

**Comment by zenixls2** [comment]
The sample files provided by the original author is quite outdated. Some information from old version of tensorflow is incompatible with the new one. You should use the new data from Reddit to train a new model. Currently I only have un-fully trained results, since I cannot get any powerful GPU server for training. I will provide a sample model in a few days, and update the steps in README file. 
Thanks for your feedback

**Comment by zenixls2** [comment]
I've updated the README to use model from the following link:
https://mega.nz/#!KI5z3JQA!WITf7HC8ISAh7tTMVdGH0fncsQHCm0s-NafuHHhVX18
If you found any other problems, please report back to me.

**Comment by dylib** [comment]
Hello, I have another question, for the server.py where is `libchatbot`? Thanks!

**Comment by zenixls2** [comment]
@dylib In `chatbot.py` there's a libchatbot function. It generates a consumer function to process the text passed in.

**Comment by dylib** [comment]
Thanks very much! :)

**Comment by brvins** [comment]
Hi Zenix,

I am trying to resolve the same error as discussed here

I have downloaded the model from the link 
https://mega.nz/#!KI5z3JQA!WITf7HC8ISAh7tTMVdGH0fncsQHCm0s-NafuHHhVX18 and placed it in the models dir as per your suggestion.

I am getting errors like 
ValueError: checkpoint not found in models/reddit.
config.pkl file not found .

Can you also upload chekpoint and other required files which should in the models dir.

I would really appreciate if you can help with this. Thank you.

**Comment by zenixls2** [comment]
@brvins 
where did you put the trained model?
the extracted data is in the folder named reddit.
just move it as `chatbot-rnn/models/reddit` should work.
you could find `config.pkl` in the reddit folder.

**Comment by brvins** [comment]
@zenixls2  I have the files chars_vocab.pkl,checkpoint,config.pkl,model.ckpt-4682964 in the directory chatbot-rnn/models/reddit . I get below error when I run chatbot.py 
NotFoundError: rnnlm/multi_rnn_cell/cell_0/gru_cell/candidate/kernel 
Can u please tell me what steps I have to do with the reddit file which u uploaded in below link
https://mega.nz/#!KI5z3JQA!WITf7HC8ISAh7tTMVdGH0fncsQHCm0s-NafuHHhVX18

**Comment by zenixls2** [comment]
@brvins 
did you create a virtual environment or install using pip with the requirements.txt in project root folder? Don't forget to source the bin/active in your virtual environment folder if you use virtual environment.
